### ISSUE TITLE
TransitManagement model: no information concerning the `trip_details` attribute

### ISSUE THREAD

**Issue by isalvadori** [smart-data-models/dataModel.UrbanMobility#22]
Hi, 
 in the `TransitManagement` model (https://github.com/smart-data-models/dataModel.UrbanMobility/blob/master/TransitManagement/model.yaml) there is no information at all about the `trip_details` attribute. There is just the type (`object`), but no `properties` nor a reference model. 

```
trip_details:
      description: 'A descriptor of realtime update on the schedule of a vehicle along a trip.'
      properties: {}
      type: object
      x-ngsi:
        type: Property
```

Would it be possible to improve its description?

Thanks!
